package:
  name: wlogdate
  version: 1.0.0
source:
  git_rev: master
  git_url: https://github.com/uym2/wLogDate.git
requirements:
  host:
    - python
    - setuptools
  
  build:
    - python
    - numpy 
    
  run:
    - python >= 3.7.3
    - numpy
    - dendropy == 4.3.0
    - scipy == 1.3.1

test:
  imports:
    - logdate

about:
  home: https://github.com/uym2/wLogDate
  license: GNU GENERAL PUBLIC LICENSE
  license_file: LICENSE
